# Generated by Django 4.0.5 on 2023-07-04 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lendapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Product Gallery',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('free_days', models.IntegerField()),
                ('rental_charge', models.IntegerField()),
                ('status', models.CharField(choices=[('Free', 'Free'), ('Lended', 'Lended')], max_length=20)),
                ('tag', models.CharField(choices=[('Featured', 'Free'), ('Latest', 'Lended')], max_length=20)),
                ('address', models.TextField()),
                ('phone_no', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(null=True)),
                ('facebook', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
                ('instagram', models.URLField(null=True)),
                ('linkedin', models.URLField(null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lendapp.category')),
                ('image', models.ManyToManyField(to='lendapp.productgallery')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lendapp.location')),
            ],
            options={
                'verbose_name': 'All Item',
            },
        ),
    ]
