# Generated by Django 4.0.5 on 2023-07-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendapp', '0006_lendproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendproduct',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
